Add frontend test coverage
dopeshot/beyond-life pull request #226
Opened 2023-07-24 10:19 UTC by coffemakingtoaster

Closes #135

2023-07-24 16:43 UTC, coffemakingtoaster commented
@Zoe-Bot Please readd the fonts I had to remove
All instances of that are marked with 
`// TODO: #135` so they are easier to find :)

2023-07-24 22:52 UTC, LarsFlieger requested changes
Very nice! Paar Kleinigkeiten! 

Das mit dem template ist sehr smart und dann noch mit dem paths im workflow trigger + die badge updaten nur wenn changes drin sind! Sehr nice! I like it!

2023-07-24 22:52 UTC, LarsFlieger commented on .github/workflows/codecov.template.yml
> +name: Build and commit codecov badge
Vielleicht was mehr generelles: "Generate and commit code coverage badge"

2023-07-24 22:52 UTC, LarsFlieger commented on frontend/content/profilelinks.ts
> +	} as any,
Ich glaube das können wir weglassen. Einfach wegmachen type kommt eh von unten.

2023-07-24 22:52 UTC, LarsFlieger commented on frontend/content/profilelinks.ts
> +	onclick?: () => void
Hier oder oben ist ein Typo. (und durch das any glaub failt es sogar, also noch mehr ein grund es wegzunehmen)
Einmal ist es onclick und einmal onClick (C groß)

2023-07-24 22:52 UTC, LarsFlieger commented on frontend/package.json
> +			"src/**/*.cy.{ts,tsx}",
die mergen mit `{cy,unit,stories}`

könnte man zusammenfassen

2023-07-24 22:52 UTC, LarsFlieger commented on frontend/src/app/globals.css
> +	src: url('/fonts/arbutus/ArbutusSlab-Regular.ttf') format('truetype');
glaub das hat eher joy gemacht @Zoe-Bot aber warum nicht einfach css import von google?

2023-07-26 08:42 UTC, LarsFlieger approved these changes
LGTM

2023-07-26 08:43 UTC, merged