Feature/219-payment-success-page
dopeshot/beyond-life pull request #229
Opened 2023-07-24 13:00 UTC by TjWaaaa

Closes #219

2023-07-24 23:02 UTC, LarsFlieger requested changes
Seite auf desktop sieht sehr nice aus! Good work! Funktioniert außer dem header auch sehr gut auf allen Geräten!

2023-07-24 23:02 UTC, LarsFlieger commented on frontend/src/app/(dynamic)/last-will/(pages)/order-confirmation/page.tsx
> +			<div>
hier die height vllt expanden lassen wenn der content größer wird:

![image](https://github.com/dopeshot/beyond-life/assets/47084064/16a49006-8e82-49ff-a9af-1985c0f21bf0)


(Das ist bei 300px width)

2023-07-24 23:02 UTC, LarsFlieger commented on frontend/src/app/(dynamic)/last-will/(pages)/order-confirmation/page.tsx
> +			<div>
was man da auch machen kann als quick fix: 

- keine pixel height angeben
- einfach dem image und dem text drunter nen großen padding geben auf desktop
- mobile kleinerer padding

dann geht die seite gut auf allen geräten. 

wenn man höhe will, dann mit min-height arbeiten.

2023-07-26 16:15 UTC, TjWaaaa commented on frontend/src/app/(dynamic)/last-will/(pages)/order-confirmation/page.tsx
> +			<div>
das bekomm ich grade nicht gefixt.. kannst du da evtl mal rienschauen? das problem ist dass der text kein child vom bild ist sondern mit absolute drauf liegt. Das bild kennt also die höhe vom text nicht. hab grade keine ideen wie man das umgeht..

2023-07-30 14:04 UTC, LarsFlieger commented on frontend/src/app/(dynamic)/last-will/(pages)/order-confirmation/page.tsx
> +			<div>
Resolved, einfach die orientierung umdrehen:
- Das bild wird absolut, h-full, w-full
- Und die size des headers orientiert sich dann am text + padding

So wie hier: https://stackoverflow.com/a/31267758/12160777

2023-07-30 14:05 UTC, LarsFlieger approved these changes
LGTM

2023-07-30 20:29 UTC, merged