Feature/success url query params
dopeshot/beyond-life pull request #305
Opened 2023-08-01 13:51 UTC by Branchverse

2023-08-01 13:54 UTC, coffemakingtoaster requested changes
Looks good, cleanup env var

2023-08-01 13:54 UTC, coffemakingtoaster commented on backend/src/payments/services/payments.service.ts
> -    if (paymentPlans[plan] < paymentPlans[user.paymentPlan]) {
"Ich schreib meinen Code sowieso von Anfang an immer so"...jajajajajajajaja

2023-08-01 13:54 UTC, coffemakingtoaster commented on backend/src/payments/services/stripe.service.ts
> +          'STRIPE_SUCCESS_URL',
This means the STRIPE_CANCEL_ENV variable can be removed, no?

2023-08-01 13:56 UTC, Branchverse commented on backend/src/payments/services/payments.service.ts
> -    if (paymentPlans[plan] < paymentPlans[user.paymentPlan]) {
Ich schon, Copilot nicht

2023-08-01 13:57 UTC, coffemakingtoaster commented on backend/src/payments/services/stripe.service.ts
> +          'STRIPE_SUCCESS_URL',
It is already dupliacted with the "FRONTEND_DOMAIN" env var...we dont need 3 Vars containing almost the exact same value

2023-08-01 20:12 UTC, Branchverse commented on backend/sample.env
> +STRIPE_REDIRECT_URL=/last-will/order-confirmation
wdym

2023-08-01 20:12 UTC, Branchverse commented on backend/sample.env
> +STRIPE_REDIRECT_URL=/last-will/order-confirmation
ah

2023-08-02 07:23 UTC, coffemakingtoaster approved these changes
LGTM

2023-08-02 12:41 UTC, merged